replicaCount: 2

image:
  repository: <your-ecr-account>.dkr.ecr.us-east-1.amazonaws.com/my-portfolio
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  host: portfolio.stepin.ink
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi