name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: | 
          docker build -t ${{secrets.REGISTRY_USER}}/portfolio:${{github.run_number}} .
          docker build -t ${{secrets.REGISTRY_USER}}/portfolio:latest .

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.REGISTRY_PASS }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin

      # 🔥 NEW STEP
      - name: Ensure repo exists
        run: |
          curl -X POST https://hub.docker.com/v2/repositories/${{ secrets.REGISTRY_USER }}/portfolio/ \
          -H "Content-Type: application/json" \
          -u "${{ secrets.REGISTRY_USER }}:${{ secrets.REGISTRY_PASS }}" \
          -d '{"name": "portfolio"}' || true

      - name: Push image 
        run: |
          docker push ${{secrets.REGISTRY_USER}}/portfolio:${{github.run_number}}
          docker push ${{secrets.REGISTRY_USER}}/portfolio:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull ${{secrets.REGISTRY_USER}}/portfolio:${{github.run_number}}
            docker rm -f resume || true
            docker run -d --name resume -p 8080:5001 ${{secrets.REGISTRY_USER}}/portfolio:${{github.run_number}}